### ISSUE TITLE
bug: segfault in process cache

### ISSUE THREAD

**Issue by willfindlay** [cilium/tetragon#1232]
Noticed the following segmentation fault in the sensors/tracing tests while testing #1223.

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x19dfd02]

goroutine 982 [running]:
github.com/cilium/tetragon/pkg/process.(*Cache).get(0xc001a56cf0?, {0xc002a62d50, 0x10})
	/home/runner/work/tetragon/tetragon/go/src/github.com/cilium/tetragon/pkg/process/cache.go:165 +0x22
github.com/cilium/tetragon/pkg/process.Get(...)
	/home/runner/work/tetragon/tetragon/go/src/github.com/cilium/tetragon/pkg/process/process.go:356
github.com/cilium/tetragon/pkg/grpc/exec.(*MsgExecveEventUnix).Retry(0xc00095f5e0, 0x2?, {0x23af760, 0xc004729860})
	/home/runner/work/tetragon/tetragon/go/src/github.com/cilium/tetragon/pkg/grpc/exec/exec.go:[195](https://github.com/cilium/tetragon/actions/runs/5554635581/jobs/10144675422?pr=1223#step:7:196) +0x14a
github.com/cilium/tetragon/pkg/eventcache.(*Cache).handleEvents(0xc00308ddc0)
	/home/runner/work/tetragon/tetragon/go/src/github.com/cilium/tetragon/pkg/eventcache/eventcache.go:122 +0x18d
github.com/cilium/tetragon/pkg/eventcache.(*Cache).loop(0xc00308ddc0)
	/home/runner/work/tetragon/tetragon/go/src/github.com/cilium/tetragon/pkg/eventcache/eventcache.go:161 +0x268
created by github.com/cilium/tetragon/pkg/eventcache.NewWithTimer
	/home/runner/work/tetragon/tetragon/go/src/github.com/cilium/tetragon/pkg/eventcache/eventcache.go:225 +0x1a5
```

**Comment by kkourt** [comment]
Maybe it's related to https://github.com/cilium/tetragon/pull/1042
