### ISSUE TITLE
ci:test: panic on sensors/tracing tests

### ISSUE THREAD

**Issue by tixxdz** [cilium/tetragon#2110]
One of the PRs failed with sensors test https://github.com/cilium/tetragon/actions/runs/7923388627/job/21633163518?pr=1986 could relate on how the event cache is operated in tests

```
time="2024-02-15T23:12:20Z" level=info msg="map was unloaded" map=execve_calls pin=execve_calls
time="2024-02-15T23:12:20Z" level=info msg="map was unloaded" map=tcpmon_map pin=tcpmon_map
time="2024-02-15T23:12:20Z" level=info msg="map was unloaded" map=tg_conf_map pin=tg_conf_map
time="2024-02-15T23:12:20Z" level=info msg="map was unloaded" map=tg_stats_map pin=tg_stats_map
Calling lseek...
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1edfb80]

goroutine 225 [running]:
github.com/cilium/tetragon/pkg/process.(*Cache).get(0x400429f400?, {0x4003a3a948, 0x8})
	/home/runner/actions-runner/_work/tetragon/tetragon/go/src/github.com/cilium/tetragon/pkg/process/cache.go:150 +0x20
github.com/cilium/tetragon/pkg/process.Get(...)
	/home/runner/actions-runner/_work/tetragon/tetragon/go/src/github.com/cilium/tetragon/pkg/process/process.go:492
github.com/cilium/tetragon/pkg/grpc/exec.(*MsgExecveEventUnix).Retry(0x40001b9120, 0x400429f400, {0x2ef6500, 0x400433b040})
	/home/runner/actions-runner/_work/tetragon/tetragon/go/src/github.com/cilium/tetragon/pkg/grpc/exec/exec.go:214 +0x14c
github.com/cilium/tetragon/pkg/eventcache.(*Cache).handleEvents(0x4003fd4c40)
	/home/runner/actions-runner/_work/tetragon/tetragon/go/src/github.com/cilium/tetragon/pkg/eventcache/eventcache.go:135 +0x148
github.com/cilium/tetragon/pkg/eventcache.(*Cache).loop(0x4003fd4c40)
	/home/runner/actions-runner/_work/tetragon/tetragon/go/src/github.com/cilium/tetragon/pkg/eventcache/eventcache.go:176 +0x21c
created by github.com/cilium/tetragon/pkg/eventcache.NewWithTimer in goroutine 222
	/home/runner/actions-runner/_work/tetragon/tetragon/go/src/github.com/cilium/tetragon/pkg/eventcache/eventcache.go:239 +0x1c4
FAIL	github.com/cilium/tetragon/pkg/sensors/tracing	77.463s
```

**Comment by tixxdz** [comment]
Closing as flake, didn't happen again
