### ISSUE TITLE
CI failure on `TestExecThreads`, might be flaky

### ISSUE THREAD

**Issue by mtardy** [cilium/tetragon#3187]
See https://github.com/cilium/tetragon/actions/runs/12008004447/job/33469767131?pr=3163

[logs_31291043166.zip](https://github.com/user-attachments/files/18028198/logs_31291043166.zip)

**Comment by kkourt** [comment]
This is not exactly a failure, the test passes but there is a panic because t.Log is called after a test is completed:

```
PASS
panic: Log in goroutine after TestExecThreads has completed: deleting export file for TestExecThreads (/tmp/tetragon.gotest.TestExecThreads.4165764240.json)

goroutine 429 [running]:
testing.(*common).logDepth(0x400445e9c0, {0x4003d74060, 0x5f}, 0x3)
	/opt/hostedtoolcache/go/1.23.3/arm64/src/testing/testing.go:1029 +0x3cc
testing.(*common).log(...)
	/opt/hostedtoolcache/go/1.23.3/arm64/src/testing/testing.go:1011
testing.(*common).Logf(0x400445e9c0, {0x1dc5591?, 0x10?}, {0x4003e9a000?, 0xffffffffffffff01?, 0x400083c410?})
	/opt/hostedtoolcache/go/1.23.3/arm64/src/testing/testing.go:1062 +0x5c
github.com/cilium/tetragon/pkg/testutils.(*ExportFile).Close(0x4001fdc540)
	/home/runner/work/tetragon/tetragon/go/src/github.com/cilium/tetragon/pkg/testutils/filenames.go:49 +0x32c
github.com/cilium/tetragon/pkg/server.(*Server).GetEventsWG(0x4001bfe0a0, 0x40001bc280, {0x2157da0, 0x4001bfe0f0}, {0x2126f40, 0x4001fdc540}, 0x40014900c0)
	/home/runner/work/tetragon/tetragon/go/src/github.com/cilium/tetragon/pkg/server/server.go:214 +0x874
github.com/cilium/tetragon/pkg/exporter.(*Exporter).Start.func1()
	/home/runner/work/tetragon/tetragon/go/src/github.com/cilium/tetragon/pkg/exporter/exporter.go:48 +0x44
created by github.com/cilium/tetragon/pkg/exporter.(*Exporter).Start in goroutine 426
	/home/runner/work/tetragon/tetragon/go/src/github.com/cilium/tetragon/pkg/exporter/exporter.go:47 +0xac
FAIL	github.com/cilium/tetragon/pkg/sensors/exec	105.324s
FAIL
make: *** [Makefile:261: test] Error 1
```

Or at least that's what I get from above.
Also happened in https://github.com/cilium/tetragon/pull/3219 (the error is the same)

**Comment by mtardy** [comment]
Might have been fixed according to Kev
