### ISSUE TITLE
tetra getevents deadlock

### ISSUE THREAD

**Issue by michi-covalent** [cilium/tetragon#492]
tetragon version: quay.io/cilium/tetragon:v0.8.2

tetragon got into a state where `tetra getevents` hangs without returning any events.

[stack.txt](https://github.com/cilium/tetragon/files/9824824/stack.txt)

**Comment by kkourt** [comment]
I thought above might be the same issue that #510 solves, but this seems to be a different deadlock.

So a bunch of `AddListener` calls seem to be stuck waiting for the ProcessManager lock.

<details>

```
goroutine 84596 [semacquire, 3 minutes]:
sync.runtime_SemacquireMutex(0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0xc001d1a738)
	/usr/local/go/src/sync/mutex.go:162 +0x165
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:81
github.com/cilium/tetragon/pkg/grpc.(*ProcessManager).AddListener(0xc001d1a720, {0x213ec00?, 0xc00062a3a0})
	/go/src/github.com/cilium/tetragon/pkg/grpc/process_manager.go:75 +0xdf
github.com/cilium/tetragon/pkg/server.(*Server).GetEventsWG(0xc0016b7480, 0xc009266b00, {0x2162030, 0xc0091f2550}, {0x0, 0x0}, 0x0)
	/go/src/github.com/cilium/tetragon/pkg/server/server.go:120 +0x296
github.com/cilium/tetragon/pkg/server.(*Server).GetEvents(0xc005a7e9c0?, 0x1d4e420?, {0x2162030?, 0xc0091f2550?})
	/go/src/github.com/cilium/tetragon/pkg/server/server.go:98 +0x2b
github.com/cilium/tetragon/api/v1/tetragon._FineGuidanceSensors_GetEvents_Handler({0x1d7a0e0?, 0xc0016b7480}, {0x2160e20, 0xc005a7e9c0})
	/go/src/github.com/cilium/tetragon/vendor/github.com/cilium/tetragon/api/v1/tetragon/sensors_grpc.pb.go:239 +0xd0
google.golang.org/grpc.(*Server).processStreamingRPC(0xc001185680, {0x2164740, 0xc002f451e0}, 0xc0055b4900, 0xc001d1a930, 0x2fb3880, 0x0)
	/go/src/github.com/cilium/tetragon/vendor/google.golang.org/grpc/server.go:1558 +0xf46
google.golang.org/grpc.(*Server).handleStream(0xc001185680, {0x2164740, 0xc002f451e0}, 0xc0055b4900, 0x0)
	/go/src/github.com/cilium/tetragon/vendor/google.golang.org/grpc/server.go:1640 +0x9d6
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/go/src/github.com/cilium/tetragon/vendor/google.golang.org/grpc/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/github.com/cilium/tetragon/vendor/google.golang.org/grpc/server.go:930 +0x28a
	
goroutine 84555 [semacquire, 5 minutes]:
sync.runtime_SemacquireMutex(0x0?, 0x0?, 0x0?)
	/usr/local/go/src/runtime/sema.go:71 +0x25
sync.(*Mutex).lockSlow(0xc001d1a738)
	/usr/local/go/src/sync/mutex.go:162 +0x165
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:81
github.com/cilium/tetragon/pkg/grpc.(*ProcessManager).AddListener(0xc001d1a720, {0x213ec00?, 0xc000010320})
	/go/src/github.com/cilium/tetragon/pkg/grpc/process_manager.go:75 +0xdf
github.com/cilium/tetragon/pkg/server.(*Server).GetEventsWG(0xc0016b7480, 0xc00906bc80, {0x2162030, 0xc009231e90}, {0x0, 0x0}, 0x0)
	/go/src/github.com/cilium/tetragon/pkg/server/server.go:120 +0x296
github.com/cilium/tetragon/pkg/server.(*Server).GetEvents(0xc0059b1450?, 0x1d4e420?, {0x2162030?, 0xc009231e90?})
	/go/src/github.com/cilium/tetragon/pkg/server/server.go:98 +0x2b
github.com/cilium/tetragon/api/v1/tetragon._FineGuidanceSensors_GetEvents_Handler({0x1d7a0e0?, 0xc0016b7480}, {0x2160e20, 0xc0059b1450})
	/go/src/github.com/cilium/tetragon/vendor/github.com/cilium/tetragon/api/v1/tetragon/sensors_grpc.pb.go:239 +0xd0
google.golang.org/grpc.(*Server).processStreamingRPC(0xc001185680, {0x2164740, 0xc003045a00}, 0xc0057bb8c0, 0xc001d1a930, 0x2fb3880, 0x0)
	/go/src/github.com/cilium/tetragon/vendor/google.golang.org/grpc/server.go:1558 +0xf46
google.golang.org/grpc.(*Server).handleStream(0xc001185680, {0x2164740, 0xc003045a00}, 0xc0057bb8c0, 0x0)
	/go/src/github.com/cilium/tetragon/vendor/google.golang.org/grpc/server.go:1640 +0x9d6
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/go/src/github.com/cilium/tetragon/vendor/google.golang.org/grpc/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/github.com/cilium/tetragon/vendor/google.golang.org/grpc/server.go:930 +0x28a

```
</details>

OK, so who holds the lock?

Seems to be goroutine 65 which is stuck in:
```
goroutine 65 [chan send, 47 minutes]:
github.com/cilium/tetragon/pkg/server.(*getEventsListener).Notify(0xc001d21a78?, 0x1d5e880?)
	/go/src/github.com/cilium/tetragon/pkg/server/server.go:72 +0x26
github.com/cilium/tetragon/pkg/grpc.(*ProcessManager).NotifyListener(0xc001e99e10?, {0x1c2ef80, 0xc001e99e10}, 0xc001d21b58?)
	/go/src/github.com/cilium/tetragon/pkg/grpc/process_manager.go:91 +0xf9
```

That is, in:
```
func (l *getEventsListener) Notify(res *tetragon.GetEventsResponse) {
	l.events <- res
}
```

The loop that handles requests from this channel is in `GetEventsWG` and at least some instances of this function seem to be stuck in grpc code, that we can't really control:
```
goroutine 82988 [select, 47 minutes]:
google.golang.org/grpc/internal/transport.(*writeQuota).get(0xc008692980, 0x583)
	/go/src/github.com/cilium/tetragon/vendor/google.golang.org/grpc/internal/transport/flowcontrol.go:59 +0x6e
google.golang.org/grpc/internal/transport.(*http2Server).Write(0xc005d02340, 0xc005861560, {0xc001f1af00, 0x5, 0x5}, {0xc008eae100, 0x57e, 0x57e}, 0x0?)
	/go/src/github.com/cilium/tetragon/vendor/google.golang.org/grpc/internal/transport/http2_server.go:1096 +0x16a
google.golang.org/grpc.(*serverStream).SendMsg(0xc00553bd40, {0x1d82b00?, 0xc005a96ea0})
	/go/src/github.com/cilium/tetragon/vendor/google.golang.org/grpc/stream.go:1543 +0x1c2
github.com/cilium/tetragon/api/v1/tetragon.(*fineGuidanceSensorsGetEventsServer).Send(0xc00062b3a8?, 0x1?)
	/go/src/github.com/cilium/tetragon/vendor/github.com/cilium/tetragon/api/v1/tetragon/sensors_grpc.pb.go:252 +0x2b
github.com/cilium/tetragon/pkg/server.(*Server).GetEventsWG(0xc0016b7480, 0xc008c71c00, {0x2162030, 0xc00795bbd0}, {0x0, 0x0}, 0x0)
	/go/src/github.com/cilium/tetragon/pkg/server/server.go:151 +0x623
github.com/cilium/tetragon/pkg/server.(*Server).GetEvents(0xc00553bd40?, 0x1d4e420?, {0x2162030?, 0xc00795bbd0?})
	/go/src/github.com/cilium/tetragon/pkg/server/server.go:98 +0x2b
github.com/cilium/tetragon/api/v1/tetragon._FineGuidanceSensors_GetEvents_Handler({0x1d7a0e0?, 0xc0016b7480}, {0x2160e20, 0xc00553bd40})
	/go/src/github.com/cilium/tetragon/vendor/github.com/cilium/tetragon/api/v1/tetragon/sensors_grpc.pb.go:239 +0xd0
google.golang.org/grpc.(*Server).processStreamingRPC(0xc001185680, {0x2164740, 0xc005d02340}, 0xc005861560, 0xc001d1a930, 0x2fb3880, 0x0)
	/go/src/github.com/cilium/tetragon/vendor/google.golang.org/grpc/server.go:1558 +0xf46
google.golang.org/grpc.(*Server).handleStream(0xc001185680, {0x2164740, 0xc005d02340}, 0xc005861560, 0x0)
	/go/src/github.com/cilium/tetragon/vendor/google.golang.org/grpc/server.go:1640 +0x9d6
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/go/src/github.com/cilium/tetragon/vendor/google.golang.org/grpc/server.go:932 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/github.com/cilium/tetragon/vendor/google.golang.org/grpc/server.go:930 +0x28a
```
